const theme = {
    font: {
        fontLight: 'BaiJamjureeLight',
        fontRegular: 'BaiJamjureeRegular',
        fontMedium: 'BaiJamjureeMedium',
        fontBold: 'BaiJamjureeBold',
    },
    color: {
        textColor: '#ffffff',
        textColorInactive: '#94a2b9',
        textColorActive: '#F9B919',
        colorLinearGradient: 'linear-gradient(90.93deg, #e0b954 15.31%, #e8cd62 96.49%)',
        activeColor: '#e0b954',
        inactiveColor: '#94a2b9',
        backgroundColor: 'rgba(32,32,32,0.6)',
        backgroundColorSecond: '#F1F3F6',
        linkColor: '#0E78F5',
        colorBtn: '#ffffff',
        colorBtnActive: '#000000',
        borderColor: '#262626',
        bgModal: 'rgba(0,0,0,0.4)',
        tableHeadColor: 'rgba(32,32,32,1)',
    },
    images: {
        logo: require('./icon/logo.svg'),
        dotSildeActive: require('./icon/dotSildeActive.svg'),
        dotSlideDeactive: require('./icon/dotSlideDeactive.svg'),
        homeA: require('./icon/homeA.svg'),
        transferA: require('./icon/transferA.svg'),
        gameA: require('./icon/gameA.svg'),
        home: require('./icon/home.svg'),
        transfer: require('./icon/transfer.svg'),
        game: require('./icon/game.svg'),
        menu: require('./icon/menu.svg'),
        user: require('./icon/user.svg'),
        userA: require('./icon/userA.svg'),
        logout: require('./icon/logout.svg'),
        right: require('./icon/right.svg'),
        close: require('./icon/close.svg'),
        x: require('./icon/x.png'),
        o: require('./icon/o.png'),
        loading: require('./icon/loading.svg'),
        recent: require('./icon/recent.svg'),
        arrowDown: require('./icon/arrowDown.svg'),
        add: require('./icon/add.svg'),
    },
};

export default theme;
